### ISSUE TITLE
Rely on `window.caches`

### ISSUE THREAD

**Issue by TimvdLippe** [preview-code/github-ajax#1]
The implementation relies on the service-worker for evergreen browsers. The service-worker also caches the responses with `caches.put` etc...

It would be better to directly use the cache in the element, since the `cache` is also available there (it is not specific to the service-worker). This would remove the need for the shared [`responseCache`](https://github.com/preview-code/github-ajax/blob/a7c73751b4ec763708b591f56f7147c46aef8c07/github-ajax.html#L42), as well as the duplicate cache in the service-worker. See https://developer.mozilla.org/nl/docs/Web/API/Cache#Browser_compatibility for the compatibility of browsers and see if you find it worth it :smile:

**Comment by txsmith** [comment]
So if I understand correctly, this would involve 'moving' some of the caching behavior from service worker into this element. Am i right?

**Comment by TimvdLippe** [comment]
Yes. So it mostly concerns modifying the current caching logic with the proper `cache.match`. Therefore the `service-worker` only concerns pre-caching of pages and not caching of data.
